"""Bundle this repo's docs, labs, and policies into site/data/content.js.

The explorer pages (site/*.html) never duplicate repo content: they read it
from this generated bundle, so the site always reflects the Markdown/code in
the repo. Re-run this after changing any file outside site/:

    python site/build.py

Standard library only. The GitHub Pages workflow runs it on every push, so
the committed bundle only matters for opening the pages locally (file://).
"""

from __future__ import annotations

import base64
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "data" / "content.js"

TEXT_SUFFIXES = {".md", ".py", ".yaml", ".yml", ".sh", ".txt", ".toml", ".json"}
TEXT_NAMES = {"Dockerfile", "LICENSE"}
IMAGE_TYPES = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".svg": "image/svg+xml", ".gif": "image/gif"}
SKIP_PREFIXES = ("site/", ".git/")


def tracked_files() -> list[str]:
    """Prefer git's view of the repo (skips untracked scratch files); fall
    back to a filesystem walk when git isn't available."""
    try:
        out = subprocess.run(
            ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout
        return [line for line in out.splitlines() if line]
    except (OSError, subprocess.CalledProcessError):
        files = []
        for dirpath, dirnames, filenames in os.walk(ROOT):
            dirnames[:] = [d for d in dirnames if d not in {".git", "node_modules", ".venv", "__pycache__"}]
            for name in filenames:
                files.append(Path(dirpath, name).relative_to(ROOT).as_posix())
        return files


def repo_url() -> str:
    """https URL of the GitHub repo, from GITHUB_REPOSITORY (Actions) or the
    origin remote. Empty string if neither is available."""
    if os.environ.get("GITHUB_REPOSITORY"):
        return f"https://github.com/{os.environ['GITHUB_REPOSITORY']}"
    try:
        url = subprocess.run(
            ["git", "remote", "get-url", "origin"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except (OSError, subprocess.CalledProcessError):
        return ""
    url = re.sub(r"^git@github\.com:", "https://github.com/", url)
    return re.sub(r"\.git$", "", url)


def main() -> None:
    files: dict[str, str] = {}
    assets: dict[str, str] = {}

    for rel in sorted(tracked_files()):
        if rel.startswith(SKIP_PREFIXES):
            continue
        path = ROOT / rel
        if not path.is_file():
            continue
        suffix = path.suffix.lower()
        if suffix in TEXT_SUFFIXES or path.name in TEXT_NAMES:
            files[rel] = path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
        elif suffix in IMAGE_TYPES:
            data = base64.b64encode(path.read_bytes()).decode("ascii")
            assets[rel] = f"data:{IMAGE_TYPES[suffix]};base64,{data}"

    bundle = {
        "generated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "repo": {"url": repo_url(), "branch": os.environ.get("GITHUB_REF_NAME", "main")},
        "files": files,
        "assets": assets,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(bundle, ensure_ascii=False, separators=(",", ":"))
    # "</" can't appear inside a <script>-loaded file's string literals safely
    # if this is ever inlined; escaping it keeps the bundle inline-safe too.
    payload = payload.replace("</", "<\\/")
    OUT.write_text(
        "/* Generated by site/build.py - do not edit by hand. */\n"
        f"window.PLAYBOOK_CONTENT = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT.relative_to(ROOT).as_posix()}: {len(files)} text files, {len(assets)} images")


if __name__ == "__main__":
    main()
